### ISSUE TITLE
parseo del mapa

### ISSUE THREAD

**Issue by amorilla42** [amorilla42/cub3d#4]
Mapa:

El mapa tiene que quedar a lo ultimo del archivo

NO pueden haber saltos de línea extra ni espacios

muros son 1

vacio son 0

personaje (orientacion) N S W E

tiene que estar rodeado de muros

**Comment by jdomingu98** [comment]
Las texturas son tipo XPM42, que cambia algo la estructura del fichero. Vas a tener que cambiar un poco el parseo.
